### ISSUE TITLE
Mute alarms

### ISSUE THREAD

**Issue by mgates86** [aws/amazon-managed-service-for-prometheus-roadmap#10]
Need ability to mute servers doing maintenance

**Comment by ampabhi-aws** [comment]
Hey @mgates86,

Thank you for submitting this feature request! Have you checked out the silencing APIs that are exposed as a part of the Amazon Managed Service for Prometheus Alert Manager component? That should allow you to create scheduled silences that will mute alarms during maintenance windows. You can learn more about the Silencing API here: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-APIReference.html#AMP-APIReference-Prometheus-Compatible-Apis. Would this solve your use case?

We're also working on improving our integration with the Grafana Unified Alerting UI, so you can silence your alarms directly from Grafana.

**Comment by ampabhi-aws** [comment]
https://github.com/aws/amazon-managed-service-for-prometheus-roadmap/issues/3

**Comment by ampabhi-aws** [comment]
Here is the related ticket for the integration with Grafana Unified Alerting: https://github.com/aws/amazon-managed-service-for-prometheus-roadmap/issues/3
