### ISSUE TITLE
 Cloud Computing Compliance Controls Catalog (C5)

### ISSUE THREAD

**Issue by haarchri** [aws/amazon-managed-service-for-prometheus-roadmap#13]
Any Plans to add Cloud Computing Compliance Controls Catalog (C5)? We have a need for German/Banking Organisation

**Comment by jeromeinsf** [comment]
The service has started the compliance certification programs, which include C5.

**Comment by jeromeinsf** [comment]
https://aws.amazon.com/compliance/services-in-scope/C5/
