### ISSUE TITLE
Document or raise size limit for HELP text

### ISSUE THREAD

**Issue by antifuchs** [aws/amazon-managed-service-for-prometheus-roadmap#17]
I'm trying to ingest metrics from cockroachdb into aws managed prometheus, and it throws a fatal error for the HELP text that I reported in https://github.com/cockroachdb/cockroach/issues/87112.

I couldn't find the size limit for HELP text that AMP mandates, but more than that I find it a bit unfortunate that there is a size limit in the first place (prometheus knows no way to truncate help metadata that it ingests, and the only way to successfully ingest metrics is to not send any metadata at all).

I would wish for one of two outcomes here:
* You all raise the size limit for HELP text (docs are good, right?), or
* documentation is added for the size limit, and the error message points to that documentation

**Comment by ampabhi-aws** [comment]
Thanks @antifuchs for this issue! I'm circling up internally, and will try to follow up soon.

**Comment by ampabhi-aws** [comment]
Seems like the change was made on the cockroachDB side: https://github.com/cockroachdb/cockroach/issues/87112#issuecomment-1232630356

The official limit: Maximum length accepted for metric metadata, which includes metric name, HELP, and UNIT: 1024 bytes
(https://docs.aws.amazon.com/prometheus/latest/userguide/AMP_quotas.html)
