### ISSUE TITLE
implement present_over_time() range function

### ISSUE THREAD

**Issue by elasticdotventures** [aws/amazon-managed-service-for-prometheus-roadmap#19]
https://prometheus.io/docs/prometheus/latest/querying/functions/

The present_over_time() alarm described in the Prometheus docs is not implemented. 
I'm going to implement this using the "absent_over_time" 

```
An error occurred (ValidationException) when calling the PutRuleGroupsNamespace operation: Invalid RuleGroupsNamespace data: [309:13: group "system", rule 1, "mytest_firealarm": could not parse expression: 1:1: parse error: unknown function with name "present_over_time"]
```

**Comment by ampabhi-aws** [comment]
This has now been fixed! Closing the ticket. @alvinlin123
