### ISSUE TITLE
Custom storage retention

### ISSUE THREAD

**Issue by mhausenblas** [aws/amazon-managed-service-for-prometheus-roadmap#2]
Currently, the maximum retention time for ingested metrics into an Amazon Managed Service for Prometheus workspace is fixed. That is, data older than [150 days](https://docs.aws.amazon.com/prometheus/latest/userguide/AMP_quotas.html) is deleted from the workspace.

With custom storage retention, users would have the ability to change the metrics data retention period on a per-workspace basis.  The feature would be exposed via the AWS console, API, CloudFormation, and Terraform.

**Comment by davidferdinand** [comment]
For us having at least 13 months worth of storage would allow for annual comparison of data trends etc.
If this is on the roadmap do you have any dates around this?

**Comment by ampabhi-aws** [comment]
@davidferdinand, what type of annual comparison were you looking to do with extended storage? Are you looking to do a long term trend over a year, or more of a week today to a week in the past comparison?

**Comment by davidferdinand** [comment]
@ampabhi-aws probably both, we would have teams who would be interested to see how data might shift with the seasons, and others who might want to do a comparison of this week against this week last year

**Comment by neyp** [comment]
It'd be even better if you support downsampling for long-term data (e.g., past 90 days) as well.

**Comment by ampabhi-aws** [comment]
We now support the ability to change your retention period via a service limit increase: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP_quotas.html.

I'll create another ticket for downsampling/long-term-trending analysis.

**Comment by ampabhi-aws** [comment]
https://github.com/aws/amazon-managed-service-for-prometheus-roadmap/issues/23
