### ISSUE TITLE
Alert Manager integration with Grafana Unified Alerting

### ISSUE THREAD

**Issue by mhausenblas** [aws/amazon-managed-service-for-prometheus-roadmap#3]
Customers have highlighted that they want to be able to use the same Grafana UI they use build dashboards to:

* visualize their currently firing alerts,
* look at the rules they have installed, and 
* silence alarms.
 
With this feature, we consider enhancements around the integration of Amazon Managed Service for Prometheus’s Alertmanager with Grafana’s [Alert Management](https://grafana.com/docs/grafana/latest/alerting/).

Initially, we plan enabling customers to view, list and silence alarms. Further, we consider to work towards enabling create, update, and delete workflows through the Grafana UI.

**Comment by maulikpandey** [comment]
It would be great if the `expr` and `for` fields from alert rules are provided in the output of alert manager. Currently, users like us have to create two new annotations (`expr`, `for`) in addition to actual `expr` and `for` fields in all alert rules. We build Grafana URL using these annotations but it would be ideal if alert manager automatically provides them out of the box.

**Comment by ampabhi-aws** [comment]
Splitting out your comment @maulikpandey into another feature request around having better dashboard/explore tab url hooks for the AMP Alert Manager. Tracked in this issue: https://github.com/aws/amazon-managed-service-for-prometheus-roadmap/issues/8

**Comment by ampabhi-aws** [comment]
We have submitted a PR (that has been merged) to Grafana open source to enable sigv4 authentication on the Alertmanager data source. This allows you to connect the Alertmanager datasource to AMP's alert manager APIs, and allows you to integrate Grafana Unified Alerting with AMP. Here is the Grafana PR: https://github.com/grafana/grafana/pull/49718. It's currently slated to be included in the 9.1.0 release of Grafana.

**Comment by hussain-ujjaini** [comment]
@ampabhi-aws @wbrowne Can we please release it, it's open from more than 6 months now

**Comment by elasticdotventures** [comment]
fwiw @mhausenblas @ampabhi-aws  
this doesn't seem to work on the AWS Managed Prometheus version of cortex with release 9.1.1 

https://github.com/grafana/grafana/pull/49718#issuecomment-1219197253

Any guidance as to how to get this working? 
getting "Health check failed"

**Comment by elasticdotventures** [comment]
@mhausenblas 

You can probably close this. I've been able to get SigV4 Alert manager as a datasource.
I saw that Amazon Managed Grafana recently announced that it supports AlertManager as well:

https://aws.amazon.com/blogs/mt/announcing-prometheus-alertmanager-rules-in-amazon-managed-grafana/
