### ISSUE TITLE
Revise the custom storage retention solution

### ISSUE THREAD

**Issue by joshjp-aws** [aws/amazon-managed-service-for-prometheus-roadmap#30]
Reviewing some past issues opened I can see there was already a similar issue opened that has been closed, see reference [1]. However, the way it seems to work is a bit cumbersome as well as this appears to basically just open a ticket to AWS Support with this request. This really doesn't seem like ideal behavior, in an ideal world users should be able to define this when creating a workspace and this does not seem like something users should have to speak with support to do. I think there's a need to take a look at this and revise the implementation to something more user friendly.

Additionally, the way this is worded in reference [2] doesn't seem to suggest that this retention period can be reduced. There are some cases where users won't want logs to be stored for 150+ days and in those cases the user should be able to decrease this retention period. If this does already allow users to request a limit decrease please clarify the wording in reference [2] to make this clear as it looks like its only for increases the way it is currently worded.

References:
    [1]: https://github.com/aws/amazon-managed-service-for-prometheus-roadmap/issues/2
    [2]: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP_quotas.html

**Comment by kthvar** [comment]
Quotas page has been corrected to reflect this: https://docs.aws.amazon.com/prometheus/latest/userguide/AMP_quotas.html
