### ISSUE TITLE
DescribeLoggingConfiguration is missing from ReadOnlyAccess policy

### ISSUE THREAD

**Issue by johnnorro** [aws/amazon-managed-service-for-prometheus-roadmap#33]
The AWS-managed IAM policy [ReadOnlyAccess](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/ReadOnlyAccess.html) as of version 100, does not contain the action for `aps:DescribeLoggingConfiguration`. This seems an oversight as other actions such as `aps:DescribeWorkspace` and `aps:DescribeRuleGroupsNamespace` are present.

https://docs.aws.amazon.com/aws-managed-policy/latest/reference/ReadOnlyAccess.html

Is it possible to get this added in, please?

**Comment by alvinlin123** [comment]
@johnnorro thanks for letting us know. We will have it added in.

**Comment by alvinlin123** [comment]
The policy is updated. Thank you again for opening this issue @johnnorro !
