### ISSUE TITLE
Use AMP to federate data from multiple EKS clusters

### ISSUE THREAD

**Issue by hetpats** [aws/amazon-managed-service-for-prometheus-roadmap#37]
Hello,
WE want to use AMP to monitor multiple EKS clusters in our environment *all non prod reports to non prod AMP and all prod clusters report to prod AMP.
1) Is this setup possible? * we have setup prometheus server, node exporter in each eks cluster and they all report to AMP, but not sure how to validate this.
2) IF possible how / what do we need to change in the a) individual prometheus server setup in each cluster 
b) any change needed on Workspace configuration?
3) IF possible then how do i generate per cluster dash boards in AMG ?
Thank You 
HP

**Comment by jeromeinsf** [comment]
While https://aws.amazon.com/blogs/containers/multi-cluster-cost-monitoring-using-kubecost-with-amazon-eks-and-amazon-managed-service-for-prometheus/ is dedicated to cost, the general idea to use AMP to monitor multiple EKS clusters is the same.
